---
title: "R Notebook"
output: html_notebook
---

# KNN Classifier

In this practice we will use "caret" library to formulate a classification model.

## Library imports

```{r results='hide'}
library(tidyverse)
library(caret)
```

## Reading dataset

```{r results='hide'}
dataset <- read.csv2("divorce/divorce.csv", sep = ",", dec = ".", quote = "\"", header = TRUE)
```

## Descriptive information

```{r}
# Datatypes and basic descriptive information
head(dataset_reduction)

# Basic information
summary(dataset_reduction)

# Standard deviation
apply(dataset, 2, sd)

# Correlation matrix
library(RColorBrewer)
library(corrplot)

correlation <- cor(dataset)
corrplot(correlation)
```

## Training model

```{r}
train_control = trainControl(method = "cv", number = 10)

knn_model_reduction = train(Class ~ .,
                  data = dataset_reduction,
                  method = "knn",
                  tuneGrid = expand.grid(k = 1:30),
                  trControl = train_control,
                  preProcess = c("scale", "center"))

knn_model = train(Class ~ .,
                  data = dataset,
                  method = "knn",
                  tuneGrid = expand.grid(k = 1:30),
                  trControl = train_control,
                  preProcess = c("scale", "center"))
```

# Model results

```{r}
plot(knn_model_reduction)
plot(knn_model, ylim = c(0.8, 1))
```

# Some predictions

```{r}
# Data to predict
data_test <- data.frame(Atr1 = 1, Atr2 = 1, Atr3 = 1)
prediction <- predict(knn_model_reduction, newdata = data_test)
```

